// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DatabaseSpaceTravel.Models;

public partial class Logger
{
    public int Id { get; set; }

    public string Point { get; set; }

    public DateTime Date { get; set; }

    public string Level { get; set; }

    public string Message { get; set; }
}