// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DatabaseSpaceTravel.Models;

public partial class RegionRf
{
    public string Code { get; set; }

    public string RegNumber { get; set; }

    public string Oktmo { get; set; }

    public string CodeRus3 { get; set; }

    public string CodeLat2 { get; set; }

    public string CodeLat23 { get; set; }

    public string CodeLat3 { get; set; }

    public string CodeDigital { get; set; }

    public string NameRu { get; set; }

    public string NameEn { get; set; }

    public decimal? Version { get; set; }

    public virtual ICollection<City> City { get; set; } = new List<City>();
}