// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DatabaseSpaceTravel.Models;

public partial class StatusAviaCarrier
{
    public string Code { get; set; }

    public string NameRu { get; set; }

    public string NameEn { get; set; }

    public string Remark { get; set; }

    public virtual ICollection<AviaCarrier> AviaCarrier { get; set; } = new List<AviaCarrier>();
}