// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class Country
    {
        public Country()
        {
            AviaCarrier = new HashSet<AviaCarrier>();
            City = new HashSet<City>();
            RailCarrier = new HashSet<RailCarrier>();
            RailwayStation = new HashSet<RailwayStation>();
            VoucherDestinationCountryNavigation = new HashSet<Voucher>();
            VoucherLeavingCountryNavigation = new HashSet<Voucher>();
        }

        public string Code { get; set; }
        public string CodeLet2 { get; set; }
        public string CodeLet3 { get; set; }
        public string CodeLet3Ru { get; set; }
        public string CodeOksm { get; set; }
        public string ShortNameRu { get; set; }
        public string ShortNameEn { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public string Remark { get; set; }
        public decimal? Version { get; set; }

        public virtual ICollection<AviaCarrier> AviaCarrier { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<RailCarrier> RailCarrier { get; set; }
        public virtual ICollection<RailwayStation> RailwayStation { get; set; }
        public virtual ICollection<Voucher> VoucherDestinationCountryNavigation { get; set; }
        public virtual ICollection<Voucher> VoucherLeavingCountryNavigation { get; set; }
    }
}