// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class RailwayStation
    {
        public string Code { get; set; }
        public string Locode { get; set; }
        public string Oktmo { get; set; }
        public string EsrCode { get; set; }
        public string ExpressCode { get; set; }
        public string CodeUic { get; set; }
        public string CodeCountry { get; set; }
        public string CodeCity { get; set; }
        public string ShortNameRu { get; set; }
        public string ShortNameEn { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public string RoadNumber { get; set; }
        public string RoadName { get; set; }
        public string Remark { get; set; }
        public decimal? Version { get; set; }

        public virtual City CodeCityNavigation { get; set; }
        public virtual Country CodeCountryNavigation { get; set; }
    }
}