// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class StatusAviaCarrier
    {
        public StatusAviaCarrier()
        {
            AviaCarrier = new HashSet<AviaCarrier>();
        }

        public string Code { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public string Remark { get; set; }

        public virtual ICollection<AviaCarrier> AviaCarrier { get; set; }
    }
}