// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class StatusRailCarrier
    {
        public StatusRailCarrier()
        {
            RailCarrier = new HashSet<RailCarrier>();
        }

        public short Code { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public string Remark { get; set; }

        public virtual ICollection<RailCarrier> RailCarrier { get; set; }
    }
}