// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class StatusVoucher
    {
        public StatusVoucher()
        {
            Voucher = new HashSet<Voucher>();
        }

        public int Code { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }

        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}