// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class Voucher
    {
        public long Code { get; set; }
        public string Number { get; set; }
        public int StatusVoucher { get; set; }
        public int? TourAgent { get; set; }
        public DateTime? TripStartDate { get; set; }
        public DateTime? TripEndDate { get; set; }
        public string Comment { get; set; }
        public string VoucherType { get; set; }
        public string Order { get; set; }
        public int? Partner { get; set; }
        public string LeavingCity { get; set; }
        public string DestinationCity { get; set; }
        public string LeavingCountry { get; set; }
        public string DestinationCountry { get; set; }
        public string Travelers { get; set; }

        public virtual City DestinationCityNavigation { get; set; }
        public virtual Country DestinationCountryNavigation { get; set; }
        public virtual City LeavingCityNavigation { get; set; }
        public virtual Country LeavingCountryNavigation { get; set; }
        public virtual ReceivingParty PartnerNavigation { get; set; }
        public virtual StatusVoucher StatusVoucherNavigation { get; set; }
        public virtual TourAgency TourAgentNavigation { get; set; }
    }
}