// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.DataSpaceTravel.Models
{
    public partial class VoucherType
    {
        public string Code { get; set; }
        public string CodeIata { get; set; }
        public string CodeOta { get; set; }
        public string CodeRf { get; set; }
        public string NameRu { get; set; }
        public string NameEn { get; set; }
        public string Remark { get; set; }
        public decimal? Version { get; set; }
    }
}