// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SpaceTravelVoucher.Main.Models
{
    public partial class VUsers
    {
        [Display(Name = "First name")]
        public string FirstName { get; set; }

        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Last name")]
        public string LastName { get; set; }

        [Display(Name = "Username")]
        public string UserName { get; set; }

        [Key]
        public string Id { get; set; }

        [Display(Name = "Name role")]
        public string Name { get; set; }
    }


}