// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.API.Models;

public partial class Client
{
    public long Code { get; set; }

    public string Lname { get; set; }

    public string Name { get; set; }

    public string Login { get; set; }

    public string Mail { get; set; }

    public string Password { get; set; }
}