// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.API.Models;

public partial class Country
{
    public string Code { get; set; }

    public string CodeLet2 { get; set; }

    public string CodeLet3 { get; set; }

    public string CodeLet3Ru { get; set; }

    public string CodeOksm { get; set; }

    public string ShortNameRu { get; set; }

    public string ShortNameEn { get; set; }

    public string NameRu { get; set; }

    public string NameEn { get; set; }

    public string Remark { get; set; }

    public decimal? Version { get; set; }

    public virtual ICollection<AviaCarrier> AviaCarrier { get; set; } = new List<AviaCarrier>();

    public virtual ICollection<City> City { get; set; } = new List<City>();

    public virtual ICollection<RailCarrier> RailCarrier { get; set; } = new List<RailCarrier>();

    public virtual ICollection<RailwayStation> RailwayStation { get; set; } = new List<RailwayStation>();

    public virtual ICollection<Voucher> VoucherDestinationCountryNavigation { get; set; } = new List<Voucher>();

    public virtual ICollection<Voucher> VoucherLeavingCountryNavigation { get; set; } = new List<Voucher>();
}