// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.API.Models;

public partial class IdentityDocumentType
{
    public string Code { get; set; }

    public string CodeEae { get; set; }

    public string Type { get; set; }

    public string NameRu { get; set; }

    public string NameEn { get; set; }

    public string Remark { get; set; }

    public decimal? Version { get; set; }
}