// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.API.Models;

public partial class StatusRailCarrier
{
    public short Code { get; set; }

    public string NameRu { get; set; }

    public string NameEn { get; set; }

    public string Remark { get; set; }

    public virtual ICollection<RailCarrier> RailCarrier { get; set; } = new List<RailCarrier>();
}