// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.API.Models;

public partial class TourAgency
{
    public int Code { get; set; }

    public string NameRu { get; set; }

    public string NameEn { get; set; }

    public string NumberPhone { get; set; }

    public string Mail { get; set; }

    public string Inn { get; set; }

    public string Address { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Voucher> Voucher { get; set; } = new List<Voucher>();
}