// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SpaceTravelVoucher.API.Models;

public partial class VoucherXml
{
    public string XmlVoucher { get; set; }
    public string CodeAuth { get; set; }
}