//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
    public partial class InvalidContent : SmevFault
    {
        
        private InvalidContentValidationError[] validationErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValidationError", Order=0)]
        public InvalidContentValidationError[] ValidationError
        {
            get
            {
                return this.validationErrorField;
            }
            set
            {
                this.validationErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
    public partial class InvalidContentValidationError
    {
        
        private int errorPositionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int errorPosition
        {
            get
            {
                return this.errorPositionField;
            }
            set
            {
                this.errorPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SmevFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidContent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessDataTypeIsNotSupported))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic")]
    public partial class Void
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidContent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BusinessDataTypeIsNotSupported))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic")]
    public partial class SmevFault : Void
    {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
    public partial class BusinessDataTypeIsNotSupported : SmevFault
    {
        
        private string rootElementLocalNameField;
        
        private string rootElementNamespaceURIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RootElementLocalName
        {
            get
            {
                return this.rootElementLocalNameField;
            }
            set
            {
                this.rootElementLocalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RootElementNamespaceURI
        {
            get
            {
                return this.rootElementNamespaceURIField;
            }
            set
            {
                this.rootElementNamespaceURIField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange", ConfigurationName="ServiceReference1.EPMessageExchangePortType")]
    public interface EPMessageExchangePortType
    {
        
        // CODEGEN: Создается контракт сообщения, так как пространство имен частей сообщения (urn://artefacts-russiatourism-ru/services/message-exchange/types) не соответствует значению по умолчанию (urn://artefacts-russiatourism-ru/services/message-exchange).
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetResponse", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.InvalidContent), Action="urn:GetResponse", Name="InvalidContent", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.Void), Action="urn:GetResponse", Name="ConsumerIsNotRegistered", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.Void), Action="urn:GetResponse", Name="UnknownMessageType", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.Void), Action="urn:GetResponse", Name="EPFailure", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Void))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GetResponseResponse")]
        ServiceReference1.GetResponseResponse1 GetResponse(ServiceReference1.GetResponse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetResponseResponse1> GetResponseAsync(ServiceReference1.GetResponse request);
        
        // CODEGEN: Создается контракт сообщения, так как пространство имен частей сообщения (urn://artefacts-russiatourism-ru/services/message-exchange/types) не соответствует значению по умолчанию (urn://artefacts-russiatourism-ru/services/message-exchange).
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.Void), Action="urn:SendRequest", Name="AccessDenied", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.InvalidContent), Action="urn:SendRequest", Name="InvalidContent", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.Void), Action="urn:SendRequest", Name="ConsumerIsNotRegistered", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.BusinessDataTypeIsNotSupported), Action="urn:SendRequest", Name="BusinessDataTypeIsNotSupported", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference1.Void), Action="urn:SendRequest", Name="EPFailure", Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/faults")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Void))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SendRequestResponse")]
        ServiceReference1.SendRequestResponse1 SendRequest(ServiceReference1.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SendRequestResponse1> SendRequestAsync(ServiceReference1.SendRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class GetResponseRequest
    {
        
        private SenderProvidedGetResponseData senderProvidedGetResponseDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SenderProvidedGetResponseData SenderProvidedGetResponseData
        {
            get
            {
                return this.senderProvidedGetResponseDataField;
            }
            set
            {
                this.senderProvidedGetResponseDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class SenderProvidedGetResponseData
    {
        
        private Sender senderField;
        
        private RequestReference requestReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sender Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic", Order=1)]
        public RequestReference RequestReference
        {
            get
            {
                return this.requestReferenceField;
            }
            set
            {
                this.requestReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class Sender
    {
        
        private string mnemonicField;
        
        private string humanReadableNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mnemonic
        {
            get
            {
                return this.mnemonicField;
            }
            set
            {
                this.mnemonicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HumanReadableName
        {
            get
            {
                return this.humanReadableNameField;
            }
            set
            {
                this.humanReadableNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic")]
    public partial class RequestReference
    {
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class GetResponseResponse
    {
        
        private MessageMetadata messageMetadataField;
        
        private GetResponseResponseResponseMessage responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageMetadata MessageMetadata
        {
            get
            {
                return this.messageMetadataField;
            }
            set
            {
                this.messageMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GetResponseResponseResponseMessage ResponseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class MessageMetadata
    {
        
        private string requestIdField;
        
        private System.DateTime sendingTimestampField;
        
        private System.DateTime deliveryTimestampField;
        
        private bool deliveryTimestampFieldSpecified;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime SendingTimestamp
        {
            get
            {
                return this.sendingTimestampField;
            }
            set
            {
                this.sendingTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DeliveryTimestamp
        {
            get
            {
                return this.deliveryTimestampField;
            }
            set
            {
                this.deliveryTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryTimestampSpecified
        {
            get
            {
                return this.deliveryTimestampFieldSpecified;
            }
            set
            {
                this.deliveryTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class GetResponseResponseResponseMessage
    {
        
        private Response responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Response Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class Response
    {
        
        private SenderProvidedResponseData senderProvidedResponseDataField;
        
        private MessageMetadata messageMetadataField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SenderProvidedResponseData SenderProvidedResponseData
        {
            get
            {
                return this.senderProvidedResponseDataField;
            }
            set
            {
                this.senderProvidedResponseDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MessageMetadata MessageMetadata
        {
            get
            {
                return this.messageMetadataField;
            }
            set
            {
                this.messageMetadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class SenderProvidedResponseData
    {
        
        private RequestReference requestReferenceField;
        
        private System.Xml.XmlElement messagePrimaryContentField;
        
        private SenderProvidedResponseDataRequestRejectedReason[] requestRejectedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic", Order=0)]
        public RequestReference RequestReference
        {
            get
            {
                return this.requestReferenceField;
            }
            set
            {
                this.requestReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic", Order=1)]
        public System.Xml.XmlElement MessagePrimaryContent
        {
            get
            {
                return this.messagePrimaryContentField;
            }
            set
            {
                this.messagePrimaryContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RequestRejectedReason", IsNullable=false)]
        public SenderProvidedResponseDataRequestRejectedReason[] RequestRejected
        {
            get
            {
                return this.requestRejectedField;
            }
            set
            {
                this.requestRejectedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class SenderProvidedResponseDataRequestRejectedReason
    {
        
        private string rejectionReasonCodeField;
        
        private string rejectionReasonDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RejectionReasonCode
        {
            get
            {
                return this.rejectionReasonCodeField;
            }
            set
            {
                this.rejectionReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RejectionReasonDescription
        {
            get
            {
                return this.rejectionReasonDescriptionField;
            }
            set
            {
                this.rejectionReasonDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResponse", WrapperNamespace="urn://artefacts-russiatourism-ru/services/message-exchange", IsWrapped=true)]
    public partial class GetResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
        public ServiceReference1.GetResponseRequest GetResponseRequest;
        
        public GetResponse()
        {
        }
        
        public GetResponse(ServiceReference1.GetResponseRequest GetResponseRequest)
        {
            this.GetResponseRequest = GetResponseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResponseResponse", WrapperNamespace="urn://artefacts-russiatourism-ru/services/message-exchange", IsWrapped=true)]
    public partial class GetResponseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
        public ServiceReference1.GetResponseResponse GetResponseResponse;
        
        public GetResponseResponse1()
        {
        }
        
        public GetResponseResponse1(ServiceReference1.GetResponseResponse GetResponseResponse)
        {
            this.GetResponseResponse = GetResponseResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class SendRequestRequest
    {
        
        private SenderProvidedRequestData senderProvidedRequestDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SenderProvidedRequestData SenderProvidedRequestData
        {
            get
            {
                return this.senderProvidedRequestDataField;
            }
            set
            {
                this.senderProvidedRequestDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class SenderProvidedRequestData
    {
        
        private Sender senderField;
        
        private System.Xml.XmlElement messagePrimaryContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Sender Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types/basic", Order=1)]
        public System.Xml.XmlElement MessagePrimaryContent
        {
            get
            {
                return this.messagePrimaryContentField;
            }
            set
            {
                this.messagePrimaryContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
    public partial class SendRequestResponse
    {
        
        private MessageMetadata messageMetadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MessageMetadata MessageMetadata
        {
            get
            {
                return this.messageMetadataField;
            }
            set
            {
                this.messageMetadataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRequest", WrapperNamespace="urn://artefacts-russiatourism-ru/services/message-exchange", IsWrapped=true)]
    public partial class SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
        public ServiceReference1.SendRequestRequest SendRequestRequest;
        
        public SendRequest()
        {
        }
        
        public SendRequest(ServiceReference1.SendRequestRequest SendRequestRequest)
        {
            this.SendRequestRequest = SendRequestRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendRequestResponse", WrapperNamespace="urn://artefacts-russiatourism-ru/services/message-exchange", IsWrapped=true)]
    public partial class SendRequestResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://artefacts-russiatourism-ru/services/message-exchange/types")]
        public ServiceReference1.SendRequestResponse SendRequestResponse;
        
        public SendRequestResponse1()
        {
        }
        
        public SendRequestResponse1(ServiceReference1.SendRequestResponse SendRequestResponse)
        {
            this.SendRequestResponse = SendRequestResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface EPMessageExchangePortTypeChannel : ServiceReference1.EPMessageExchangePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EPMessageExchangePortTypeClient : System.ServiceModel.ClientBase<ServiceReference1.EPMessageExchangePortType>, ServiceReference1.EPMessageExchangePortType
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EPMessageExchangePortTypeClient() : 
                base(EPMessageExchangePortTypeClient.GetDefaultBinding(), EPMessageExchangePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EPMessageExchangeEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPMessageExchangePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(EPMessageExchangePortTypeClient.GetBindingForEndpoint(endpointConfiguration), EPMessageExchangePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPMessageExchangePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EPMessageExchangePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPMessageExchangePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EPMessageExchangePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EPMessageExchangePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.GetResponseResponse1 ServiceReference1.EPMessageExchangePortType.GetResponse(ServiceReference1.GetResponse request)
        {
            return base.Channel.GetResponse(request);
        }
        
        public ServiceReference1.GetResponseResponse GetResponse(ServiceReference1.GetResponseRequest GetResponseRequest)
        {
            ServiceReference1.GetResponse inValue = new ServiceReference1.GetResponse();
            inValue.GetResponseRequest = GetResponseRequest;
            ServiceReference1.GetResponseResponse1 retVal = ((ServiceReference1.EPMessageExchangePortType)(this)).GetResponse(inValue);
            return retVal.GetResponseResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetResponseResponse1> ServiceReference1.EPMessageExchangePortType.GetResponseAsync(ServiceReference1.GetResponse request)
        {
            return base.Channel.GetResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetResponseResponse1> GetResponseAsync(ServiceReference1.GetResponseRequest GetResponseRequest)
        {
            ServiceReference1.GetResponse inValue = new ServiceReference1.GetResponse();
            inValue.GetResponseRequest = GetResponseRequest;
            return ((ServiceReference1.EPMessageExchangePortType)(this)).GetResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.SendRequestResponse1 ServiceReference1.EPMessageExchangePortType.SendRequest(ServiceReference1.SendRequest request)
        {
            return base.Channel.SendRequest(request);
        }
        
        public ServiceReference1.SendRequestResponse SendRequest(ServiceReference1.SendRequestRequest SendRequestRequest)
        {
            ServiceReference1.SendRequest inValue = new ServiceReference1.SendRequest();
            inValue.SendRequestRequest = SendRequestRequest;
            ServiceReference1.SendRequestResponse1 retVal = ((ServiceReference1.EPMessageExchangePortType)(this)).SendRequest(inValue);
            return retVal.SendRequestResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SendRequestResponse1> ServiceReference1.EPMessageExchangePortType.SendRequestAsync(ServiceReference1.SendRequest request)
        {
            return base.Channel.SendRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SendRequestResponse1> SendRequestAsync(ServiceReference1.SendRequestRequest SendRequestRequest)
        {
            ServiceReference1.SendRequest inValue = new ServiceReference1.SendRequest();
            inValue.SendRequestRequest = SendRequestRequest;
            return ((ServiceReference1.EPMessageExchangePortType)(this)).SendRequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EPMessageExchangeEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EPMessageExchangeEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://10.111.13.18/tran/ws/EPMessageExchangeWS");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EPMessageExchangePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.EPMessageExchangeEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EPMessageExchangePortTypeClient.GetEndpointAddress(EndpointConfiguration.EPMessageExchangeEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            EPMessageExchangeEndpoint,
        }
    }
}
