//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace SpaceTravelVoucher.DataGisEisEp.EPMessageExchangeWS.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher", IsNullable = false)]
    public partial class CreateVoucherRequest
    {

        private CreateVoucherRequestVoucher voucherField;

        /// <remarks/>
        public CreateVoucherRequestVoucher Voucher
        {
            get
            {
                return this.voucherField;
            }
            set
            {
                this.voucherField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherRequestVoucher
    {

        private string numberField;

        private voucherStatus statusField;

        private CreateVoucherRequestVoucherTourAgent tourAgentField;

        private System.DateTime tripStartDateField;

        private bool tripStartDateFieldSpecified;

        private System.DateTime tripEndDateField;

        private bool tripEndDateFieldSpecified;

        private string commentField;

        private dictionaryType voucherTypeField;

        private CreateVoucherRequestVoucherOrder orderField;

        private partnerType partnerField;

        private dictionaryType leavingCityField;

        private dictionaryType destinationCityField;

        private dictionaryType leavingCountryField;

        private dictionaryType destinationCountryField;

        private travelerType[] travelersField;

        /// <remarks/>
        public string number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        public voucherStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public CreateVoucherRequestVoucherTourAgent TourAgent
        {
            get
            {
                return this.tourAgentField;
            }
            set
            {
                this.tourAgentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime tripStartDate
        {
            get
            {
                return this.tripStartDateField;
            }
            set
            {
                this.tripStartDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tripStartDateSpecified
        {
            get
            {
                return this.tripStartDateFieldSpecified;
            }
            set
            {
                this.tripStartDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime tripEndDate
        {
            get
            {
                return this.tripEndDateField;
            }
            set
            {
                this.tripEndDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tripEndDateSpecified
        {
            get
            {
                return this.tripEndDateFieldSpecified;
            }
            set
            {
                this.tripEndDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        public dictionaryType VoucherType
        {
            get
            {
                return this.voucherTypeField;
            }
            set
            {
                this.voucherTypeField = value;
            }
        }

        /// <remarks/>
        public CreateVoucherRequestVoucherOrder Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }

        /// <remarks/>
        public partnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        public dictionaryType LeavingCity
        {
            get
            {
                return this.leavingCityField;
            }
            set
            {
                this.leavingCityField = value;
            }
        }

        /// <remarks/>
        public dictionaryType DestinationCity
        {
            get
            {
                return this.destinationCityField;
            }
            set
            {
                this.destinationCityField = value;
            }
        }

        /// <remarks/>
        public dictionaryType LeavingCountry
        {
            get
            {
                return this.leavingCountryField;
            }
            set
            {
                this.leavingCountryField = value;
            }
        }

        /// <remarks/>
        public dictionaryType DestinationCountry
        {
            get
            {
                return this.destinationCountryField;
            }
            set
            {
                this.destinationCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Traveler", IsNullable = false)]
        public travelerType[] Travelers
        {
            get
            {
                return this.travelersField;
            }
            set
            {
                this.travelersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public enum voucherStatus
    {

        /// <remarks/>
        CONFIRMED,

        /// <remarks/>
        CANCELLED,

        /// <remarks/>
        USED,

        /// <remarks/>
        SUSPENDED,

        /// <remarks/>
        RESERVED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherRequestVoucherTourAgent
    {

        private string innField;

        /// <remarks/>
        public string inn
        {
            get
            {
                return this.innField;
            }
            set
            {
                this.innField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class partnerType
    {

        private string codeField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(soleProprietorCustomerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(individualCustomerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(travelerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class individualType
    {

        private string lastNameField;

        private string firstNameField;

        private string patronymicField;

        private dictionaryType identityDocumentTypeField;

        private string identityDocumentSeriesNumberField;

        private dictionaryType identityDocumentIssueCountryField;

        private string phoneNumberField;

        private string emailField;

        /// <remarks/>
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string patronymic
        {
            get
            {
                return this.patronymicField;
            }
            set
            {
                this.patronymicField = value;
            }
        }

        /// <remarks/>
        public dictionaryType IdentityDocumentType
        {
            get
            {
                return this.identityDocumentTypeField;
            }
            set
            {
                this.identityDocumentTypeField = value;
            }
        }

        /// <remarks/>
        public string identityDocumentSeriesNumber
        {
            get
            {
                return this.identityDocumentSeriesNumberField;
            }
            set
            {
                this.identityDocumentSeriesNumberField = value;
            }
        }

        /// <remarks/>
        public dictionaryType IdentityDocumentIssueCountry
        {
            get
            {
                return this.identityDocumentIssueCountryField;
            }
            set
            {
                this.identityDocumentIssueCountryField = value;
            }
        }

        /// <remarks/>
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class dictionaryType
    {

        private string codeField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class soleProprietorCustomerType : individualType
    {

        private string innField;

        private string addressField;

        /// <remarks/>
        public string inn
        {
            get
            {
                return this.innField;
            }
            set
            {
                this.innField = value;
            }
        }

        /// <remarks/>
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class individualCustomerType : individualType
    {

        private string addressField;

        /// <remarks/>
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class travelerType : individualType
    {

        private System.DateTime birthDateField;

        private bool birthDateFieldSpecified;

        private travelerTypeAccommodationTourismService[] accommodationTourismServicesField;

        private travelerTypeRailTransportationTourismService[] railTransportationTourismServicesField;

        private travelerTypeAirTransportationTourismService[] airTransportationTourismServicesField;

        private travelerTypeTransportationTourismService[] transportationTourismServicesField;

        private travelerTypeTourismService[] tourismServicesField;

        private string travelerIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AccommodationTourismService", IsNullable = false)]
        public travelerTypeAccommodationTourismService[] AccommodationTourismServices
        {
            get
            {
                return this.accommodationTourismServicesField;
            }
            set
            {
                this.accommodationTourismServicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RailTransportationTourismService", IsNullable = false)]
        public travelerTypeRailTransportationTourismService[] RailTransportationTourismServices
        {
            get
            {
                return this.railTransportationTourismServicesField;
            }
            set
            {
                this.railTransportationTourismServicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AirTransportationTourismService", IsNullable = false)]
        public travelerTypeAirTransportationTourismService[] AirTransportationTourismServices
        {
            get
            {
                return this.airTransportationTourismServicesField;
            }
            set
            {
                this.airTransportationTourismServicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TransportationTourismService", IsNullable = false)]
        public travelerTypeTransportationTourismService[] TransportationTourismServices
        {
            get
            {
                return this.transportationTourismServicesField;
            }
            set
            {
                this.transportationTourismServicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TourismService", IsNullable = false)]
        public travelerTypeTourismService[] TourismServices
        {
            get
            {
                return this.tourismServicesField;
            }
            set
            {
                this.tourismServicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string travelerId
        {
            get
            {
                return this.travelerIdField;
            }
            set
            {
                this.travelerIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class travelerTypeAccommodationTourismService
    {

        private dictionaryType accommodationCountryField;

        private dictionaryType accommodationCityField;

        private dictionaryType accommodationRegionRFField;

        private string hotelNameField;

        private string accommodationTypeField;

        private System.DateTime checkInDateField;

        private System.DateTime checkOutDateField;

        private partnerType partnerField;

        private string serviceIdField;

        /// <remarks/>
        public dictionaryType AccommodationCountry
        {
            get
            {
                return this.accommodationCountryField;
            }
            set
            {
                this.accommodationCountryField = value;
            }
        }

        /// <remarks/>
        public dictionaryType AccommodationCity
        {
            get
            {
                return this.accommodationCityField;
            }
            set
            {
                this.accommodationCityField = value;
            }
        }

        /// <remarks/>
        public dictionaryType AccommodationRegionRF
        {
            get
            {
                return this.accommodationRegionRFField;
            }
            set
            {
                this.accommodationRegionRFField = value;
            }
        }

        /// <remarks/>
        public string hotelName
        {
            get
            {
                return this.hotelNameField;
            }
            set
            {
                this.hotelNameField = value;
            }
        }

        /// <remarks/>
        public string accommodationType
        {
            get
            {
                return this.accommodationTypeField;
            }
            set
            {
                this.accommodationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime checkInDate
        {
            get
            {
                return this.checkInDateField;
            }
            set
            {
                this.checkInDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime checkOutDate
        {
            get
            {
                return this.checkOutDateField;
            }
            set
            {
                this.checkOutDateField = value;
            }
        }

        /// <remarks/>
        public partnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class travelerTypeRailTransportationTourismService
    {

        private dictionaryType railCarrierField;

        private string departureCityField;

        private string departureStationField;

        private System.DateTime departureDateField;

        private bool departureDateFieldSpecified;

        private System.DateTime departureTimeField;

        private bool departureTimeFieldSpecified;

        private string arrivalCityField;

        private string arrivalStationField;

        private System.DateTime arrivalDateField;

        private bool arrivalDateFieldSpecified;

        private System.DateTime arrivalTimeField;

        private bool arrivalTimeFieldSpecified;

        private string routeNumberField;

        private string ticketNumberField;

        private partnerType partnerField;

        private string serviceIdField;

        /// <remarks/>
        public dictionaryType RailCarrier
        {
            get
            {
                return this.railCarrierField;
            }
            set
            {
                this.railCarrierField = value;
            }
        }

        /// <remarks/>
        public string departureCity
        {
            get
            {
                return this.departureCityField;
            }
            set
            {
                this.departureCityField = value;
            }
        }

        /// <remarks/>
        public string departureStation
        {
            get
            {
                return this.departureStationField;
            }
            set
            {
                this.departureStationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime departureDate
        {
            get
            {
                return this.departureDateField;
            }
            set
            {
                this.departureDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureDateSpecified
        {
            get
            {
                return this.departureDateFieldSpecified;
            }
            set
            {
                this.departureDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime departureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureTimeSpecified
        {
            get
            {
                return this.departureTimeFieldSpecified;
            }
            set
            {
                this.departureTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string arrivalCity
        {
            get
            {
                return this.arrivalCityField;
            }
            set
            {
                this.arrivalCityField = value;
            }
        }

        /// <remarks/>
        public string arrivalStation
        {
            get
            {
                return this.arrivalStationField;
            }
            set
            {
                this.arrivalStationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime arrivalDate
        {
            get
            {
                return this.arrivalDateField;
            }
            set
            {
                this.arrivalDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalDateSpecified
        {
            get
            {
                return this.arrivalDateFieldSpecified;
            }
            set
            {
                this.arrivalDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime arrivalTime
        {
            get
            {
                return this.arrivalTimeField;
            }
            set
            {
                this.arrivalTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalTimeSpecified
        {
            get
            {
                return this.arrivalTimeFieldSpecified;
            }
            set
            {
                this.arrivalTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string routeNumber
        {
            get
            {
                return this.routeNumberField;
            }
            set
            {
                this.routeNumberField = value;
            }
        }

        /// <remarks/>
        public string ticketNumber
        {
            get
            {
                return this.ticketNumberField;
            }
            set
            {
                this.ticketNumberField = value;
            }
        }

        /// <remarks/>
        public partnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class travelerTypeAirTransportationTourismService
    {

        private dictionaryType airCarrierField;

        private string flightNumberField;

        private dictionaryType departureCityField;

        private dictionaryType departureAirportField;

        private System.DateTime departureDateField;

        private System.DateTime departureTimeField;

        private bool departureTimeFieldSpecified;

        private dictionaryType arrivalCityField;

        private dictionaryType arrivalAirportField;

        private System.DateTime arrivalDateField;

        private bool arrivalDateFieldSpecified;

        private System.DateTime arrivalTimeField;

        private bool arrivalTimeFieldSpecified;

        private string bookingReferenceField;

        private string ticketNumberField;

        private partnerType partnerField;

        private string serviceIdField;

        /// <remarks/>
        public dictionaryType AirCarrier
        {
            get
            {
                return this.airCarrierField;
            }
            set
            {
                this.airCarrierField = value;
            }
        }

        /// <remarks/>
        public string flightNumber
        {
            get
            {
                return this.flightNumberField;
            }
            set
            {
                this.flightNumberField = value;
            }
        }

        /// <remarks/>
        public dictionaryType DepartureCity
        {
            get
            {
                return this.departureCityField;
            }
            set
            {
                this.departureCityField = value;
            }
        }

        /// <remarks/>
        public dictionaryType DepartureAirport
        {
            get
            {
                return this.departureAirportField;
            }
            set
            {
                this.departureAirportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime departureDate
        {
            get
            {
                return this.departureDateField;
            }
            set
            {
                this.departureDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime departureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureTimeSpecified
        {
            get
            {
                return this.departureTimeFieldSpecified;
            }
            set
            {
                this.departureTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public dictionaryType ArrivalCity
        {
            get
            {
                return this.arrivalCityField;
            }
            set
            {
                this.arrivalCityField = value;
            }
        }

        /// <remarks/>
        public dictionaryType ArrivalAirport
        {
            get
            {
                return this.arrivalAirportField;
            }
            set
            {
                this.arrivalAirportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime arrivalDate
        {
            get
            {
                return this.arrivalDateField;
            }
            set
            {
                this.arrivalDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalDateSpecified
        {
            get
            {
                return this.arrivalDateFieldSpecified;
            }
            set
            {
                this.arrivalDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime arrivalTime
        {
            get
            {
                return this.arrivalTimeField;
            }
            set
            {
                this.arrivalTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalTimeSpecified
        {
            get
            {
                return this.arrivalTimeFieldSpecified;
            }
            set
            {
                this.arrivalTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string bookingReference
        {
            get
            {
                return this.bookingReferenceField;
            }
            set
            {
                this.bookingReferenceField = value;
            }
        }

        /// <remarks/>
        public string ticketNumber
        {
            get
            {
                return this.ticketNumberField;
            }
            set
            {
                this.ticketNumberField = value;
            }
        }

        /// <remarks/>
        public partnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class travelerTypeTransportationTourismService
    {

        private string descriptionField;

        private string departurePointField;

        private System.DateTime departureDateField;

        private bool departureDateFieldSpecified;

        private System.DateTime departureTimeField;

        private bool departureTimeFieldSpecified;

        private string arrivalPointField;

        private System.DateTime arrivalDateField;

        private bool arrivalDateFieldSpecified;

        private System.DateTime arrivalTimeField;

        private bool arrivalTimeFieldSpecified;

        private string routeNumberField;

        private string ticketNumberField;

        private partnerType partnerField;

        private string serviceIdField;

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string departurePoint
        {
            get
            {
                return this.departurePointField;
            }
            set
            {
                this.departurePointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime departureDate
        {
            get
            {
                return this.departureDateField;
            }
            set
            {
                this.departureDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureDateSpecified
        {
            get
            {
                return this.departureDateFieldSpecified;
            }
            set
            {
                this.departureDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime departureTime
        {
            get
            {
                return this.departureTimeField;
            }
            set
            {
                this.departureTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool departureTimeSpecified
        {
            get
            {
                return this.departureTimeFieldSpecified;
            }
            set
            {
                this.departureTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string arrivalPoint
        {
            get
            {
                return this.arrivalPointField;
            }
            set
            {
                this.arrivalPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime arrivalDate
        {
            get
            {
                return this.arrivalDateField;
            }
            set
            {
                this.arrivalDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalDateSpecified
        {
            get
            {
                return this.arrivalDateFieldSpecified;
            }
            set
            {
                this.arrivalDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime arrivalTime
        {
            get
            {
                return this.arrivalTimeField;
            }
            set
            {
                this.arrivalTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arrivalTimeSpecified
        {
            get
            {
                return this.arrivalTimeFieldSpecified;
            }
            set
            {
                this.arrivalTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string routeNumber
        {
            get
            {
                return this.routeNumberField;
            }
            set
            {
                this.routeNumberField = value;
            }
        }

        /// <remarks/>
        public string ticketNumber
        {
            get
            {
                return this.ticketNumberField;
            }
            set
            {
                this.ticketNumberField = value;
            }
        }

        /// <remarks/>
        public partnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class travelerTypeTourismService
    {

        private dictionaryType tourismServiceTypeField;

        private string descriptionField;

        private partnerType partnerField;

        private string serviceIdField;

        /// <remarks/>
        public dictionaryType TourismServiceType
        {
            get
            {
                return this.tourismServiceTypeField;
            }
            set
            {
                this.tourismServiceTypeField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public partnerType Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherRequestVoucherOrder
    {

        private CreateVoucherRequestVoucherOrderCustomer customerField;

        private string contractNumberField;

        private System.DateTime contractDateField;

        private bool contractDateFieldSpecified;

        private bool showCostsField;

        private bool showCostsFieldSpecified;

        private decimal costField;

        /// <remarks/>
        public CreateVoucherRequestVoucherOrderCustomer Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }

        /// <remarks/>
        public string contractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime contractDate
        {
            get
            {
                return this.contractDateField;
            }
            set
            {
                this.contractDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractDateSpecified
        {
            get
            {
                return this.contractDateFieldSpecified;
            }
            set
            {
                this.contractDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool showCosts
        {
            get
            {
                return this.showCostsField;
            }
            set
            {
                this.showCostsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showCostsSpecified
        {
            get
            {
                return this.showCostsFieldSpecified;
            }
            set
            {
                this.showCostsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherRequestVoucherOrderCustomer
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyCustomer", typeof(CreateVoucherRequestVoucherOrderCustomerCompanyCustomer))]
        [System.Xml.Serialization.XmlElementAttribute("IndividualCustomer", typeof(individualCustomerType))]
        [System.Xml.Serialization.XmlElementAttribute("SoleProprietorCustomer", typeof(soleProprietorCustomerType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherRequestVoucherOrderCustomerCompanyCustomer
    {

        private string nameField;

        private string innField;

        private string headLastNameField;

        private string headFirstNameField;

        private string headPatronymicField;

        private dictionaryType locatedCountryField;

        private string phoneNumberField;

        private string emailField;

        private string addressField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string inn
        {
            get
            {
                return this.innField;
            }
            set
            {
                this.innField = value;
            }
        }

        /// <remarks/>
        public string headLastName
        {
            get
            {
                return this.headLastNameField;
            }
            set
            {
                this.headLastNameField = value;
            }
        }

        /// <remarks/>
        public string headFirstName
        {
            get
            {
                return this.headFirstNameField;
            }
            set
            {
                this.headFirstNameField = value;
            }
        }

        /// <remarks/>
        public string headPatronymic
        {
            get
            {
                return this.headPatronymicField;
            }
            set
            {
                this.headPatronymicField = value;
            }
        }

        /// <remarks/>
        public dictionaryType LocatedCountry
        {
            get
            {
                return this.locatedCountryField;
            }
            set
            {
                this.locatedCountryField = value;
            }
        }

        /// <remarks/>
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        /// <remarks/>
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
}
