//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 

namespace SpaceTravelVoucher.DataGisEisEp.EPMessageExchangeWS.Models
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher", IsNullable = false)]
    public partial class CreateVoucherResponse
    {
        public string BodyRequest { get; set; }

        private string voucherNumberField;

        private string voucherAuthorizationCodeField;

        private System.DateTime voucherCreatedDateTimeField;

        private CreateVoucherResponseTravelers travelersField;

        /// <remarks/>
        public string voucherNumber
        {
            get
            {
                return this.voucherNumberField;
            }
            set
            {
                this.voucherNumberField = value;
            }
        }

        /// <remarks/>
        public string voucherAuthorizationCode
        {
            get
            {
                return this.voucherAuthorizationCodeField;
            }
            set
            {
                this.voucherAuthorizationCodeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime voucherCreatedDateTime
        {
            get
            {
                return this.voucherCreatedDateTimeField;
            }
            set
            {
                this.voucherCreatedDateTimeField = value;
            }
        }

        /// <remarks/>
        public CreateVoucherResponseTravelers Travelers
        {
            get
            {
                return this.travelersField;
            }
            set
            {
                this.travelersField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherResponseTravelers
    {

        private CreateVoucherResponseTravelersTraveler travelerField;

        /// <remarks/>
        public CreateVoucherResponseTravelersTraveler Traveler
        {
            get
            {
                return this.travelerField;
            }
            set
            {
                this.travelerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://artefacts-russiatourism-ru/services/message-exchange/types/CreateVoucher")]
    public partial class CreateVoucherResponseTravelersTraveler
    {

        private string travelerIdField;

        private long travelerAuthField;

        /// <remarks/>
        public string travelerId
        {
            get
            {
                return this.travelerIdField;
            }
            set
            {
                this.travelerIdField = value;
            }
        }

        /// <remarks/>
        public long travelerAuth
        {
            get
            {
                return this.travelerAuthField;
            }
            set
            {
                this.travelerAuthField = value;
            }
        }
    }
}
